### PR TITLE
Force user to enter the date, time, summary, Text

### PR DESCRIPTION
**Pull request by Yr-Nemsis**
Constraint users to only allow them to create posts when summary, text, time, and date are filled. Also, an alert message is sent when the constraint has not been met. To test the functionality: Remember to set the link to each js file to relative URLs since the absolute URLs are using the js files in the main branch, which has not been updated yet.

### CODE REVIEW

**Comment by MathElderGod** [comment]
i think i have done as you asked, but it appears not to work as intended

**Comment by MathElderGod** [comment]
this pull request cannot be merged until further investigation.

**Comment by MathElderGod** [comment]
okay, I have tested this, and it seems like it works....but it isn't the correct solution. Alert will not be available during an offline event, this is why the functionality needs to be applied to the form using an event listener on the Form itself, not on the submit button. I will discuss this more in the upcoming meeting. This works for an online event but is not as elegant or convenient as a form event listener.

**Comment by agctute** [comment]
see pull request for 68

**Pull request closed without merging**
